[package]
name = "sync_files_via_mysql"
version = "0.1.0"
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]

[dependencies]
clap = "~2.31.2"
notify = "4.0.0"
mysqlclient-sys = "~0.2.3"
log = "0.4.0-rc.1"
env_logger = "0.5.0-rc.1"
ignore = "0.4.1"

