[package]
name = "huge"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[features]
default = ["track_allocation_sizes"]
track_allocation_sizes = []

[dependencies]
parking_lot = "0.12.4"
virtual_memory = { path = "../../os/virtual_memory" }
unique_ptr = { path = "../../std_based/unique_ptr" }
static_assertions = "1.1.0"
