[package]
name = "virtual_memory"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
bitflags = "2.9.1"
static_assertions = "1.1.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.61"
features = [
    "Win32_System_Memory",
    "Win32_System_SystemInformation"
]