[package]
name = "vulkan_from_scratch"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "vulkan_from_scratch_lib"
path = "src/lib.rs"

[[bin]]
name = "vulkan_from_scratch_bin"
path = "src/main.rs"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
thiserror = "2.0.12"
vek = "0.17.1"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
