[graph]
targets = [
]

[output]
feature-depth = 1

[advisories]
ignore = [
]

[bans]
deny = [
    { name = "winapi", reason = "Use the window-rs crate instead. Best having only one of those huge crates instead of both" }
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Unicode-3.0",
]

[licenses.private]
ignore = true