[graph]
targets = [
]

[output]
feature-depth = 1

[advisories]
ignore = [
]

[bans]
deny = [
    { name = "winapi", reason = "Use the window-rs crate instead" }
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "ISC",
]

[licenses.private]
ignore = true